name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get dotnet version
      uses: dotnet --info
    - name: Add GPR Source using dotnet.exe
      run: dotnet nuget add source https://nuget.pkg.github.com/anangaur/index.json --name "GPR" -u anangaur  --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
    - name: dotnet build
      run: dotnet build
    - name: dotnet nuget push
      run: dotnet nuget push my.sample.lib\**\*.nupkg -source "GPR" -SkipDuplicate

