name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup Nuget.exe
      uses: nuget/setup-nuget@v1
    - name: Add GPR Source using nuget.exe
      run: nuget sources add -name "GPR" -Source https://nuget.pkg.github.com/anangaur/index.json -Username anangaur -Password ${{ secrets.GITHUB_TOKEN }} 
    - name: dotnet build
      run: dotnet build
    - name: nuget push
      run: nuget push my.sample.lib\**\*.nupkg -source "GPR" -SkipDuplicate
       
