name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build
      run: dotnet build
    - name: dotnet push
      run: dotnet nuget push my.sample.lib\**\*.nupkg -s "GPR" --user anangaur --password ${{ secrets.GITHUB_TOKEN }}
