name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dotnet build
      run: dotnet build
    - name: Setup Nuget.exe
      uses: warrenbuckley/Setup-Nuget@v1
    - name: nuget push
      run: |
        nuget sources add -name "GPR2" -Source https://nuget.pkg.github.com/anangaur/index.json -Username anangaur -Password ${{ secrets.GITHUB_TOKEN }}
        nuget push my.sample.lib\**\*.nupkg -Source "GPR2" -SkipDuplicate
        nuget push my.sample.lib\**\*.nupkg -Source "nuget.org" -ApiKey ${{secrets.NUGET_ORG_PUSH_ANANGAUR}} -SkipDuplicate

